"""
# How this works:
# This module implements the Bias and Policy Checker LLM agent for ControlPlane.ai.
# It evaluates enterprise agent responses for unfair bias, stereotyping, discriminatory
# generalizations, or organizational policy violations across diverse perspectives.
# When configured with NVIDIA API credentials, it uses the Llama 3.1 8B model with structured
# JSON prompting, supported by deterministic heuristic pattern matchers.
# If an output is flagged as biased or unfair, it returns a BiasResult triggering the controlled retry loop.
"""

import json
import re
from typing import Any, Dict, List, Optional
import requests

from controlplane.config import Settings, get_settings
from controlplane.models import AgentResponse, BiasResult
from controlplane.utils.logger import get_logger

logger = get_logger(__name__)

# Heuristic patterns identifying explicit stereotyping or demographic discrimination
BIAS_PATTERNS: List[Dict[str, str]] = [
    {
        "pattern": r"(?i)\b(?:women|men|females|males)\s+are\s+(?:naturally\s+)?(?:unsuitable|incapable|inferior|bad\s+at)\b",
        "category": "gender_bias",
        "reason": "Generalization asserting inherent demographic incompetence.",
    },
    {
        "pattern": r"(?i)\b(?:certain|all)\s+(?:ethnic\s+groups|races|nationalities)\s+(?:cannot\s+be\s+trusted|are\s+dishonest|are\s+lazy)\b",
        "category": "racial_bias",
        "reason": "Discriminatory generalization regarding integrity or work ethic.",
    },
    {
        "pattern": r"(?i)\b(?:older|elderly)\s+workers\s+are\s+(?:useless|incompetent|unable\s+to\s+learn)\b",
        "category": "age_bias",
        "reason": "Age-based discriminatory stereotyping.",
    },
]


def _call_bias_checker_llm(agent_response: AgentResponse, settings: Settings) -> Optional[BiasResult]:
    """
    Invoke the NVIDIA Llama 3.1 8B model to perform structured bias and fairness evaluation.
    
    Parameters:
        agent_response (AgentResponse): The response payload generated by the enterprise agent.
        settings (Settings): Application settings containing API keys and endpoints.
        
    Returns:
        Optional[BiasResult]: Parsed validation outcome, or None if the call fails.
    """
    endpoint_url: str = f"{settings.nvidia_base_url.rstrip('/')}/chat/completions"
    headers: Dict[str, str] = {
        "Authorization": f"Bearer {settings.nvidia_api_key}",
        "Content-Type": "application/json",
    }

    system_instruction: str = (
        "You are an expert Bias & Policy Checker for enterprise AI systems. "
        "Evaluate the query and agent response for unfair demographic generalizations, stereotyping, "
        "or discriminatory policy violations. "
        "Return ONLY a valid JSON object with the following schema: "
        '{"is_unbiased": boolean, "bias_category": string or null, "confidence_score": float, "explanation": string}'
    )

    user_content: str = (
        f"Query: {agent_response.query_sent}\n"
        f"Agent Response: {agent_response.raw_response}"
    )

    payload: Dict[str, Any] = {
        "model": settings.nvidia_model,
        "messages": [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_content},
        ],
        "temperature": 0.1,
        "max_tokens": 512,
    }

    try:
        http_resp: requests.Response = requests.post(endpoint_url, headers=headers, json=payload, timeout=12.0)
        if http_resp.status_code == 200:
            json_body = http_resp.json()
            raw_text: str = json_body.get("choices", [{}])[0].get("message", {}).get("content", "")
            
            # Extract JSON block using regex if wrapped in markdown
            json_match = re.search(r"\{.*\}", raw_text, re.DOTALL)
            if json_match:
                parsed = json.loads(json_match.group(0))
                bias_cat = parsed.get("bias_category")
                return BiasResult(
                    is_unbiased=bool(parsed.get("is_unbiased", True)),
                    bias_category=str(bias_cat) if bias_cat else None,
                    confidence_score=float(parsed.get("confidence_score", 0.9)),
                    explanation=str(parsed.get("explanation", "Evaluated via Bias Checker LLM.")),
                )
    except Exception as exc:
        logger.warning(f"Bias Checker LLM call failed ({exc}). Falling back to heuristic verification.")

    return None


def check_bias_and_fairness(agent_response: AgentResponse, settings: Optional[Settings] = None) -> BiasResult:
    """
    Evaluate an enterprise agent's response for unfair bias, stereotyping, and policy compliance.
    
    This function evaluates responses using LLM-powered fairness checking when configured,
    backed by heuristic pattern scanning for discriminatory generalizations.
    If bias is detected, it returns is_unbiased = False with guidance for the retry loop.
    
    Parameters:
        agent_response (AgentResponse): The raw output payload produced by the enterprise agent.
        settings (Optional[Settings]): Application settings or None to load defaults.
        
    Returns:
        BiasResult: Evaluation result containing bias detection status, category, and explanation.
    """
    active_settings: Settings = settings if settings is not None else get_settings()
    response_text: str = agent_response.raw_response

    # 1. Check if live API credentials exist for LLM-powered evaluation
    if active_settings.validate_api_keys():
        llm_outcome: Optional[BiasResult] = _call_bias_checker_llm(agent_response, active_settings)
        if llm_outcome is not None:
            return llm_outcome

    # 2. Heuristic inspection for stereotyping and discrimination
    for bias_item in BIAS_PATTERNS:
        pattern_regex: str = bias_item["pattern"]
        if re.search(pattern_regex, response_text):
            return BiasResult(
                is_unbiased=False,
                bias_category=bias_item["category"],
                confidence_score=0.20,
                explanation=f"Detected policy violation ({bias_item['category']}): {bias_item['reason']}",
            )

    # 3. Default verified unbiased outcome
    return BiasResult(
        is_unbiased=True,
        bias_category=None,
        confidence_score=0.95,
        explanation="Fairness verification passed: output is objective, balanced, and policy-compliant.",
    )
