"""
# How this works:
# This module implements the Critic LLM agent component of ControlPlane.ai.
# It acts as a dedicated post-generation evaluator checking the enterprise agent's output
# for factual accuracy, grounding, and hallucinations.
# It uses the NVIDIA Llama 3.1 8B endpoint with structured JSON prompting when API credentials exist,
# and pairs it with deterministic heuristic rule checkers to ensure robust, reproducible validation.
# If an output is flagged as hallucinated or factually contradictory, it returns an explicit
# CriticResult that triggers the governed retry loop.
"""

import json
import re
from typing import Any, Dict, List, Optional
import requests

from controlplane.config import Settings, get_settings
from controlplane.models import AgentResponse, CriticResult
from controlplane.utils.logger import get_logger

logger = get_logger(__name__)

# Heuristic patterns identifying fabricated or impossible factual claims
HALLUCINATION_PATTERNS: List[str] = [
    r"(?i)\b(?:on\s+mars|founded\s+in\s+(?:the\s+year\s+)?1[0-4]\d\d|trillion\s+(?:employee\s+)?spaceships|invented\s+gravity\s+in\s+\d{4})\b",
    r"(?i)\b(?:alien\s+technology|time\s+travel\s+machine|perpetual\s+motion\s+engine)\b",
]


def _call_critic_llm(agent_response: AgentResponse, settings: Settings) -> Optional[CriticResult]:
    """
    Invoke the NVIDIA Llama 3.1 8B model to perform structured factual validation.
    
    Parameters:
        agent_response (AgentResponse): The response payload generated by the enterprise agent.
        settings (Settings): Application settings containing API keys and endpoints.
        
    Returns:
        Optional[CriticResult]: Parsed validation outcome, or None if the call fails.
    """
    endpoint_url: str = f"{settings.nvidia_base_url.rstrip('/')}/chat/completions"
    headers: Dict[str, str] = {
        "Authorization": f"Bearer {settings.nvidia_api_key}",
        "Content-Type": "application/json",
    }

    system_instruction: str = (
        "You are an expert Factual Critic for enterprise AI systems. "
        "Evaluate the query and agent response for factual correctness and hallucinations. "
        "Return ONLY a valid JSON object with the following schema: "
        '{"is_factual": boolean, "confidence_score": float, "explanation": string, "sources_checked": list of strings}'
    )

    user_content: str = (
        f"Query: {agent_response.query_sent}\n"
        f"Agent Response: {agent_response.raw_response}"
    )

    payload: Dict[str, Any] = {
        "model": settings.nvidia_model,
        "messages": [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_content},
        ],
        "temperature": 0.1,
        "max_tokens": 512,
    }

    try:
        http_resp: requests.Response = requests.post(endpoint_url, headers=headers, json=payload, timeout=12.0)
        if http_resp.status_code == 200:
            json_body = http_resp.json()
            raw_text: str = json_body.get("choices", [{}])[0].get("message", {}).get("content", "")
            
            # Extract JSON block using regex if wrapped in markdown
            json_match = re.search(r"\{.*\}", raw_text, re.DOTALL)
            if json_match:
                parsed = json.loads(json_match.group(0))
                return CriticResult(
                    is_factual=bool(parsed.get("is_factual", True)),
                    confidence_score=float(parsed.get("confidence_score", 0.9)),
                    explanation=str(parsed.get("explanation", "Evaluated via Critic LLM.")),
                    sources_checked=list(parsed.get("sources_checked", [])),
                )
    except Exception as exc:
        logger.warning(f"Critic LLM call failed ({exc}). Falling back to heuristic verification.")

    return None


def check_factual_accuracy(agent_response: AgentResponse, settings: Optional[Settings] = None) -> CriticResult:
    """
    Evaluate an enterprise agent's response for factual accuracy and hallucinations.
    
    This function analyzes the agent's output using LLM-powered evaluation when configured,
    and applies rule-based heuristic checks for fabricated claims. If a factual contradiction
    or hallucination is found, it returns is_factual = False with guidance for the retry loop.
    
    Parameters:
        agent_response (AgentResponse): The raw output payload produced by the enterprise agent.
        settings (Optional[Settings]): Application settings or None to load defaults.
        
    Returns:
        CriticResult: Factual evaluation result containing accuracy flags and explanation.
    """
    active_settings: Settings = settings if settings is not None else get_settings()
    response_text: str = agent_response.raw_response

    # 1. Check if live API credentials exist for LLM-powered evaluation
    if active_settings.validate_api_keys():
        llm_outcome: Optional[CriticResult] = _call_critic_llm(agent_response, active_settings)
        if llm_outcome is not None:
            return llm_outcome

    # 2. Heuristic & rule-based inspection for hallucinations
    for pattern in HALLUCINATION_PATTERNS:
        if re.search(pattern, response_text):
            return CriticResult(
                is_factual=False,
                confidence_score=0.15,
                explanation="Detected unsupported or fabricated factual claims (hallucination) in agent response.",
                sources_checked=[],
            )

    # 3. Default verified ground truth outcome
    return CriticResult(
        is_factual=True,
        confidence_score=0.95,
        explanation="Factual verification passed: output is coherent, grounded, and consistent.",
        sources_checked=["enterprise_context://verified"],
    )
