[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f5"
textColor = "#09090b"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "auto"
